### ISSUE TITLE
Activation Complete!

### ISSUE THREAD

**Issue by veb** [veb/oddit#28]
Redirect user into their account already logged in. Too many hoops here.

**Comment by veb** [comment]
What I mean here is we proabbly shouldn't force the user to have to fill out their username/password after clicking the link on their email for confirmation/activation but rather redirect them to their profile already logged in. 

Thoughts @avwave and @Kingy ?

**Comment by Kingy** [comment]
Should be relatively easy shouldn't it? As part of the activation code just create the session for the user and redirect them to profile.

**Comment by veb** [comment]
Yeah but I mean do we *want* that to be the default behaviour? I'm not sure if there's security concerns surrounding it etc.

**Comment by Kingy** [comment]
I'm happy with current the workflow. Can re-open or look into this another time if needed

**Comment by veb** [comment]
Agreed
