### ISSUE TITLE
Update simplejson references to json

### ISSUE THREAD

**Issue by rattfieldnz** [veb/oddit#63]
simplejson is depreciated, so any associated references/imports need to be replaced with json.

**Comment by rattfieldnz** [comment]
Ive gone through the files in the social_auth folder and made changes, tomorrow I'll be looking for others that could have the same problem...

**Comment by veb** [comment]
Great work. You do realise you could use grep?

```grep -R "something" * ```

**Comment by veb** [comment]
Cheers for doing this @rattfieldnz
