### ISSUE TITLE
Registration not working

### ISSUE THREAD

**Issue by Kingy** [veb/oddit#69]
error at /accounts/register/
[Errno 10061] No connection could be made because the target machine actively refused it.

We get this error when trying to register a new account.

**Comment by Kingy** [comment]
Ok turns out we just need to configure the mail server properly.

@veb if you put this in the settings.py file then it'll just spit the emails out to console. Might be useful while we're just testing.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

**Comment by Kingy** [comment]
Otherwise we just need to setup SMTP server and put the settings in..

```
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Host for sending e-mail.
EMAIL_HOST = 'localhost'

# Port for sending e-mail.
EMAIL_PORT = 1025

# Optional SMTP authentication information for EMAIL_HOST.
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = False
```

**Comment by veb** [comment]
OK. I've set it up to use the veb mailserver for now.

![screen shot 2016-08-02 at 5 22 48 am](https://cloud.githubusercontent.com/assets/376245/17302824/225d85fc-5872-11e6-8caf-fa808ecbd040.png)

Next up is modifying the templates for the email as it still has placeholders in it.
