### ISSUE TITLE
Upgrade to newer django

### ISSUE THREAD

**Issue by Kingy** [veb/oddit#70]
Currently on old school 1.3. We should upgrade this to 1.9.8 (current as of writing this).

**Comment by Kingy** [comment]
Currently have 1.5 successfully working. Had to make a few changes for depreciation warnings, but no show stoppers yet.

@veb I have made a new branch 'django-upgrade' for now.

**Comment by Kingy** [comment]
1.7 is now running without issues. 1.8 is giving me a lot of warnings about stuff that will be depreciated if we upgrade to 1.9 so I'll be fixing those tomorrow.

@veb you should checkout the upgrade branch and update django to 1.7. I had a good play around and nothing broke, but it might be worth having a look.

**Comment by veb** [comment]
Yup, I'll check it out. Good work buddy.

**Comment by Kingy** [comment]
We're at a much better version now, may as well close this and do another issue at a later date if we want to upgrade.
