### ISSUE TITLE
Remove usernames - unique email for identifier

### ISSUE THREAD

**Issue by Kingy** [veb/oddit#75]
You don't really need a 'username' as such for a site like this. Email for identification purposes and Real name (first/last) for public facing. 

Maybe company name for job posts? Or maybe not depending on who is posting.

![image](https://cloud.githubusercontent.com/assets/530069/17327853/11a3d788-58c3-11e6-9c78-2cbed04a777b.png)

**Comment by Kingy** [comment]
Bit of work to do this since they changed a bit of logic in 1.5

Pretty much everything we need can be found here though:
http://stackoverflow.com/a/29638766

**Comment by veb** [comment]
Maybe I'll follow this:
https://docs.djangoproject.com/en/dev/topics/auth/customizing/#a-full-example

**Comment by veb** [comment]
While we're on this, I really like Slack's "magic link" feature. I want that for oddit as well...

**Comment by Kingy** [comment]
Look into it but don't make it a priority. Let's get it shipped before we
get fancy. Has been our problem in the past :D

**Comment by veb** [comment]
Yep, fair enough. I'll do this first, then do #76

**Comment by veb** [comment]
OK. I've decided to hell with django-registration as it's a bit old now, and out of date. I'm going to use: http://www.intenct.nl/projects/django-allauth/

**Comment by veb** [comment]
Installed django-allauth. Works perfectly for what we needed, and very customisable.
